apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: myapp-team
  namespace: argocd
spec:
  description: Project for myapp team
  # Allow the GitOps repo AND the OCI Helm repo
  sourceRepos:
    - "*"  # fine for a lab
    # - https://github.com/gMpHSpLB/Gitops-Argocd_1.git
    # - oci://ghcr.io/gmphsplb/helm-lab
  destinations:
    - server: https://172.26.44.184:6443
      namespace: myapp-dev
    - server: https://172.26.44.184:6444
      namespace: myapp-staging
    - server: https://172.26.44.184:6445
      namespace: myapp-prod
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"