apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapp-clusters
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]

  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
        values:
          environment: "{{.metadata.labels.environment}}"

  template:
    metadata:
      name: "myapp-{{.name}}"   # e.g. myapp-in-cluster
    spec:
      project: myapp-team
      sources:
        # Source 1: OCI Helm chart
        - repoURL: ghcr.io/gmphsplb/helm-lab
          chart: myapp
          targetRevision: "1.0.0"
          helm:
            valueFiles:
              - "$values/envs/{{.values.environment}}/values.yaml"

        # Source 2: GitOps repo providing $values
        - repoURL: https://github.com/gMpHSpLB/myapp-gitops_1.git
          targetRevision: main
          ref: values

      destination:
        server: "{{.server}}"                    # the cluster’s API server, e.g. https://kubernetes.default.svc
        namespace: "myapp-{{.values.environment}}"  # e.g. myapp-dev, myapp-prod

      syncPolicy:
        syncOptions:
          - CreateNamespace=true