apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapp-matrix-auto-sync
  namespace: argocd
spec:
  goTemplate: true

  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/gMpHSpLB/myapp-gitops_1.git
              revision: main
              files:
                - path: envs/dev/env-config.yaml
                - path: envs/staging/env-config.yaml
          - clusters:
              selector:
                matchLabels:
                  environment: '{{.environment}}'

  template:
    metadata:
      name: "myapp-{{.environment}}-{{.name}}"
      labels:
        environment: "{{.environment}}"
        cluster: "{{.name}}"
        requireManualPromotion: "{{ .requireManualPromotion }}"
      annotations:
        notifications.argoproj.io/subscribe.on-sync-failed.slack: "{{ .notifySlack }}"
        notifications.argoproj.io/subscribe.on-sync-failed.pagerduty: "{{ .notifyPagerduty }}"
    spec:
      project: myapp-team
      sources:
        - repoURL: ghcr.io/gmphsplb/helm-lab
          chart: myapp
          targetRevision: "{{ .chartVersion }}"
          helm:
            valueFiles:
              - "$values/envs/{{.environment}}/values.yaml"
        - repoURL: https://github.com/gMpHSpLB/myapp-gitops_1.git
          targetRevision: "{{ .revision }}"
          ref: values
      destination:
        server: "{{ .server }}"
        namespace: "{{ .namespace }}"
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - Validate=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
      ignoreDifferences:
        - group: apps
          kind: Deployment
          jsonPointers:
            - /spec/replicas